/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details> 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiAuthAdminHasPermissionPost200Response } from '../models';
// @ts-ignore
import type { ApiAuthAdminHasPermissionPostRequest } from '../models';
// @ts-ignore
import type { BanUserRequest } from '../models';
// @ts-ignore
import type { CreateUserRequest } from '../models';
// @ts-ignore
import type { ImpersonateUser200Response } from '../models';
// @ts-ignore
import type { ListUserSessions1200Response } from '../models';
// @ts-ignore
import type { ListUserSessions1Request } from '../models';
// @ts-ignore
import type { ListUsers200Response } from '../models';
// @ts-ignore
import type { ResetPassword200Response } from '../models';
// @ts-ignore
import type { RevokeUserSessionRequest } from '../models';
// @ts-ignore
import type { SetUserPasswordRequest } from '../models';
// @ts-ignore
import type { SetUserRoleRequest } from '../models';
// @ts-ignore
import type { SignOut200Response } from '../models';
// @ts-ignore
import type { SocialSignIn400Response } from '../models';
// @ts-ignore
import type { SocialSignIn403Response } from '../models';
// @ts-ignore
import type { UpdateUser1Request } from '../models';
// @ts-ignore
import type { UpdateUser200Response } from '../models';
/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Check if the user has permission
         * @param {ApiAuthAdminHasPermissionPostRequest} [apiAuthAdminHasPermissionPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthAdminHasPermissionPost: async (apiAuthAdminHasPermissionPostRequest?: ApiAuthAdminHasPermissionPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/admin/has-permission`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiAuthAdminHasPermissionPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthAdminStopImpersonatingPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/admin/stop-impersonating`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ban a user
         * @param {BanUserRequest} banUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banUser: async (banUserRequest: BanUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'banUserRequest' is not null or undefined
            assertParamExists('banUser', 'banUserRequest', banUserRequest)
            const localVarPath = `/api/auth/admin/ban-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(banUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new user
         * @param {CreateUserRequest} createUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (createUserRequest: CreateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUserRequest' is not null or undefined
            assertParamExists('createUser', 'createUserRequest', createUserRequest)
            const localVarPath = `/api/auth/admin/create-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get an existing user
         * @param {string} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (id?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/admin/get-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Impersonate a user
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impersonateUser: async (listUserSessions1Request: ListUserSessions1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listUserSessions1Request' is not null or undefined
            assertParamExists('impersonateUser', 'listUserSessions1Request', listUserSessions1Request)
            const localVarPath = `/api/auth/admin/impersonate-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listUserSessions1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List user sessions
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUserSessions1: async (listUserSessions1Request: ListUserSessions1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listUserSessions1Request' is not null or undefined
            assertParamExists('listUserSessions1', 'listUserSessions1Request', listUserSessions1Request)
            const localVarPath = `/api/auth/admin/list-user-sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listUserSessions1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List users
         * @param {string | null} [searchValue] 
         * @param {string | null} [searchField] 
         * @param {string | null} [searchOperator] 
         * @param {string | null} [limit] 
         * @param {string | null} [offset] 
         * @param {string | null} [sortBy] 
         * @param {string | null} [sortDirection] 
         * @param {string | null} [filterField] 
         * @param {string | null} [filterValue] 
         * @param {string | null} [filterOperator] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (searchValue?: string | null, searchField?: string | null, searchOperator?: string | null, limit?: string | null, offset?: string | null, sortBy?: string | null, sortDirection?: string | null, filterField?: string | null, filterValue?: string | null, filterOperator?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/admin/list-users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchValue !== undefined) {
                localVarQueryParameter['searchValue'] = searchValue;
            }

            if (searchField !== undefined) {
                localVarQueryParameter['searchField'] = searchField;
            }

            if (searchOperator !== undefined) {
                localVarQueryParameter['searchOperator'] = searchOperator;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (sortDirection !== undefined) {
                localVarQueryParameter['sortDirection'] = sortDirection;
            }

            if (filterField !== undefined) {
                localVarQueryParameter['filterField'] = filterField;
            }

            if (filterValue !== undefined) {
                localVarQueryParameter['filterValue'] = filterValue;
            }

            if (filterOperator !== undefined) {
                localVarQueryParameter['filterOperator'] = filterOperator;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a user and all their sessions and accounts. Cannot be undone.
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeUser: async (listUserSessions1Request: ListUserSessions1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listUserSessions1Request' is not null or undefined
            assertParamExists('removeUser', 'listUserSessions1Request', listUserSessions1Request)
            const localVarPath = `/api/auth/admin/remove-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listUserSessions1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke a user session
         * @param {RevokeUserSessionRequest} revokeUserSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeUserSession: async (revokeUserSessionRequest: RevokeUserSessionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'revokeUserSessionRequest' is not null or undefined
            assertParamExists('revokeUserSession', 'revokeUserSessionRequest', revokeUserSessionRequest)
            const localVarPath = `/api/auth/admin/revoke-user-session`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(revokeUserSessionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke all user sessions
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeUserSessions: async (listUserSessions1Request: ListUserSessions1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listUserSessions1Request' is not null or undefined
            assertParamExists('revokeUserSessions', 'listUserSessions1Request', listUserSessions1Request)
            const localVarPath = `/api/auth/admin/revoke-user-sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listUserSessions1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set a user\'s password
         * @param {SetUserPasswordRequest} setUserPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserPassword: async (setUserPasswordRequest: SetUserPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setUserPasswordRequest' is not null or undefined
            assertParamExists('setUserPassword', 'setUserPasswordRequest', setUserPasswordRequest)
            const localVarPath = `/api/auth/admin/set-user-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setUserPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set the role of a user
         * @param {SetUserRoleRequest} setUserRoleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserRole: async (setUserRoleRequest: SetUserRoleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setUserRoleRequest' is not null or undefined
            assertParamExists('setUserRole', 'setUserRoleRequest', setUserRoleRequest)
            const localVarPath = `/api/auth/admin/set-role`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setUserRoleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unban a user
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unbanUser: async (listUserSessions1Request: ListUserSessions1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listUserSessions1Request' is not null or undefined
            assertParamExists('unbanUser', 'listUserSessions1Request', listUserSessions1Request)
            const localVarPath = `/api/auth/admin/unban-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listUserSessions1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a user\'s details
         * @param {UpdateUser1Request} updateUser1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser1: async (updateUser1Request: UpdateUser1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUser1Request' is not null or undefined
            assertParamExists('updateUser1', 'updateUser1Request', updateUser1Request)
            const localVarPath = `/api/auth/admin/update-user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUser1Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * Check if the user has permission
         * @param {ApiAuthAdminHasPermissionPostRequest} [apiAuthAdminHasPermissionPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthAdminHasPermissionPost(apiAuthAdminHasPermissionPostRequest?: ApiAuthAdminHasPermissionPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAuthAdminHasPermissionPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthAdminHasPermissionPost(apiAuthAdminHasPermissionPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiAuthAdminHasPermissionPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthAdminStopImpersonatingPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthAdminStopImpersonatingPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiAuthAdminStopImpersonatingPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ban a user
         * @param {BanUserRequest} banUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async banUser(banUserRequest: BanUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.banUser(banUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.banUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new user
         * @param {CreateUserRequest} createUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(createUserRequest: CreateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(createUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get an existing user
         * @param {string} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(id?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Impersonate a user
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async impersonateUser(listUserSessions1Request: ListUserSessions1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImpersonateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.impersonateUser(listUserSessions1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.impersonateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List user sessions
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUserSessions1(listUserSessions1Request: ListUserSessions1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListUserSessions1200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUserSessions1(listUserSessions1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.listUserSessions1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List users
         * @param {string | null} [searchValue] 
         * @param {string | null} [searchField] 
         * @param {string | null} [searchOperator] 
         * @param {string | null} [limit] 
         * @param {string | null} [offset] 
         * @param {string | null} [sortBy] 
         * @param {string | null} [sortDirection] 
         * @param {string | null} [filterField] 
         * @param {string | null} [filterValue] 
         * @param {string | null} [filterOperator] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(searchValue?: string | null, searchField?: string | null, searchOperator?: string | null, limit?: string | null, offset?: string | null, sortBy?: string | null, sortDirection?: string | null, filterField?: string | null, filterValue?: string | null, filterOperator?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListUsers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(searchValue, searchField, searchOperator, limit, offset, sortBy, sortDirection, filterField, filterValue, filterOperator, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.listUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a user and all their sessions and accounts. Cannot be undone.
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeUser(listUserSessions1Request: ListUserSessions1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignOut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeUser(listUserSessions1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.removeUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Revoke a user session
         * @param {RevokeUserSessionRequest} revokeUserSessionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeUserSession(revokeUserSessionRequest: RevokeUserSessionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignOut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeUserSession(revokeUserSessionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.revokeUserSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Revoke all user sessions
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeUserSessions(listUserSessions1Request: ListUserSessions1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignOut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeUserSessions(listUserSessions1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.revokeUserSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Set a user\'s password
         * @param {SetUserPasswordRequest} setUserPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setUserPassword(setUserPasswordRequest: SetUserPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResetPassword200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setUserPassword(setUserPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.setUserPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Set the role of a user
         * @param {SetUserRoleRequest} setUserRoleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setUserRole(setUserRoleRequest: SetUserRoleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setUserRole(setUserRoleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.setUserRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unban a user
         * @param {ListUserSessions1Request} listUserSessions1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unbanUser(listUserSessions1Request: ListUserSessions1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unbanUser(listUserSessions1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.unbanUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update a user\'s details
         * @param {UpdateUser1Request} updateUser1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser1(updateUser1Request: UpdateUser1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser1(updateUser1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.updateUser1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * Check if the user has permission
         * @param {AdminApiApiAuthAdminHasPermissionPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthAdminHasPermissionPost(requestParameters: AdminApiApiAuthAdminHasPermissionPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthAdminHasPermissionPost200Response> {
            return localVarFp.apiAuthAdminHasPermissionPost(requestParameters.apiAuthAdminHasPermissionPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthAdminStopImpersonatingPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthAdminStopImpersonatingPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Ban a user
         * @param {AdminApiBanUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        banUser(requestParameters: AdminApiBanUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.banUser(requestParameters.banUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new user
         * @param {AdminApiCreateUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(requestParameters: AdminApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.createUser(requestParameters.createUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get an existing user
         * @param {AdminApiGetUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(requestParameters: AdminApiGetUserRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.getUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Impersonate a user
         * @param {AdminApiImpersonateUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impersonateUser(requestParameters: AdminApiImpersonateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImpersonateUser200Response> {
            return localVarFp.impersonateUser(requestParameters.listUserSessions1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * List user sessions
         * @param {AdminApiListUserSessions1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUserSessions1(requestParameters: AdminApiListUserSessions1Request, options?: RawAxiosRequestConfig): AxiosPromise<ListUserSessions1200Response> {
            return localVarFp.listUserSessions1(requestParameters.listUserSessions1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * List users
         * @param {AdminApiListUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(requestParameters: AdminApiListUsersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListUsers200Response> {
            return localVarFp.listUsers(requestParameters.searchValue, requestParameters.searchField, requestParameters.searchOperator, requestParameters.limit, requestParameters.offset, requestParameters.sortBy, requestParameters.sortDirection, requestParameters.filterField, requestParameters.filterValue, requestParameters.filterOperator, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a user and all their sessions and accounts. Cannot be undone.
         * @param {AdminApiRemoveUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeUser(requestParameters: AdminApiRemoveUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignOut200Response> {
            return localVarFp.removeUser(requestParameters.listUserSessions1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke a user session
         * @param {AdminApiRevokeUserSessionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeUserSession(requestParameters: AdminApiRevokeUserSessionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignOut200Response> {
            return localVarFp.revokeUserSession(requestParameters.revokeUserSessionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke all user sessions
         * @param {AdminApiRevokeUserSessionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeUserSessions(requestParameters: AdminApiRevokeUserSessionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignOut200Response> {
            return localVarFp.revokeUserSessions(requestParameters.listUserSessions1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * Set a user\'s password
         * @param {AdminApiSetUserPasswordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserPassword(requestParameters: AdminApiSetUserPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResetPassword200Response> {
            return localVarFp.setUserPassword(requestParameters.setUserPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Set the role of a user
         * @param {AdminApiSetUserRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserRole(requestParameters: AdminApiSetUserRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.setUserRole(requestParameters.setUserRoleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unban a user
         * @param {AdminApiUnbanUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unbanUser(requestParameters: AdminApiUnbanUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.unbanUser(requestParameters.listUserSessions1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * Update a user\'s details
         * @param {AdminApiUpdateUser1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser1(requestParameters: AdminApiUpdateUser1Request, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUser200Response> {
            return localVarFp.updateUser1(requestParameters.updateUser1Request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiAuthAdminHasPermissionPost operation in AdminApi.
 */
export interface AdminApiApiAuthAdminHasPermissionPostRequest {
    readonly apiAuthAdminHasPermissionPostRequest?: ApiAuthAdminHasPermissionPostRequest
}

/**
 * Request parameters for banUser operation in AdminApi.
 */
export interface AdminApiBanUserRequest {
    readonly banUserRequest: BanUserRequest
}

/**
 * Request parameters for createUser operation in AdminApi.
 */
export interface AdminApiCreateUserRequest {
    readonly createUserRequest: CreateUserRequest
}

/**
 * Request parameters for getUser operation in AdminApi.
 */
export interface AdminApiGetUserRequest {
    readonly id?: string
}

/**
 * Request parameters for impersonateUser operation in AdminApi.
 */
export interface AdminApiImpersonateUserRequest {
    readonly listUserSessions1Request: ListUserSessions1Request
}

/**
 * Request parameters for listUserSessions1 operation in AdminApi.
 */
export interface AdminApiListUserSessions1Request {
    readonly listUserSessions1Request: ListUserSessions1Request
}

/**
 * Request parameters for listUsers operation in AdminApi.
 */
export interface AdminApiListUsersRequest {
    readonly searchValue?: string | null

    readonly searchField?: string | null

    readonly searchOperator?: string | null

    readonly limit?: string | null

    readonly offset?: string | null

    readonly sortBy?: string | null

    readonly sortDirection?: string | null

    readonly filterField?: string | null

    readonly filterValue?: string | null

    readonly filterOperator?: string | null
}

/**
 * Request parameters for removeUser operation in AdminApi.
 */
export interface AdminApiRemoveUserRequest {
    readonly listUserSessions1Request: ListUserSessions1Request
}

/**
 * Request parameters for revokeUserSession operation in AdminApi.
 */
export interface AdminApiRevokeUserSessionRequest {
    readonly revokeUserSessionRequest: RevokeUserSessionRequest
}

/**
 * Request parameters for revokeUserSessions operation in AdminApi.
 */
export interface AdminApiRevokeUserSessionsRequest {
    readonly listUserSessions1Request: ListUserSessions1Request
}

/**
 * Request parameters for setUserPassword operation in AdminApi.
 */
export interface AdminApiSetUserPasswordRequest {
    readonly setUserPasswordRequest: SetUserPasswordRequest
}

/**
 * Request parameters for setUserRole operation in AdminApi.
 */
export interface AdminApiSetUserRoleRequest {
    readonly setUserRoleRequest: SetUserRoleRequest
}

/**
 * Request parameters for unbanUser operation in AdminApi.
 */
export interface AdminApiUnbanUserRequest {
    readonly listUserSessions1Request: ListUserSessions1Request
}

/**
 * Request parameters for updateUser1 operation in AdminApi.
 */
export interface AdminApiUpdateUser1Request {
    readonly updateUser1Request: UpdateUser1Request
}

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI {
    /**
     * Check if the user has permission
     * @param {AdminApiApiAuthAdminHasPermissionPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthAdminHasPermissionPost(requestParameters: AdminApiApiAuthAdminHasPermissionPostRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiAuthAdminHasPermissionPost(requestParameters.apiAuthAdminHasPermissionPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthAdminStopImpersonatingPost(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiAuthAdminStopImpersonatingPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ban a user
     * @param {AdminApiBanUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public banUser(requestParameters: AdminApiBanUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).banUser(requestParameters.banUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new user
     * @param {AdminApiCreateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUser(requestParameters: AdminApiCreateUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).createUser(requestParameters.createUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get an existing user
     * @param {AdminApiGetUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUser(requestParameters: AdminApiGetUserRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Impersonate a user
     * @param {AdminApiImpersonateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public impersonateUser(requestParameters: AdminApiImpersonateUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).impersonateUser(requestParameters.listUserSessions1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List user sessions
     * @param {AdminApiListUserSessions1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUserSessions1(requestParameters: AdminApiListUserSessions1Request, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).listUserSessions1(requestParameters.listUserSessions1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List users
     * @param {AdminApiListUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUsers(requestParameters: AdminApiListUsersRequest = {}, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).listUsers(requestParameters.searchValue, requestParameters.searchField, requestParameters.searchOperator, requestParameters.limit, requestParameters.offset, requestParameters.sortBy, requestParameters.sortDirection, requestParameters.filterField, requestParameters.filterValue, requestParameters.filterOperator, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a user and all their sessions and accounts. Cannot be undone.
     * @param {AdminApiRemoveUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeUser(requestParameters: AdminApiRemoveUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).removeUser(requestParameters.listUserSessions1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Revoke a user session
     * @param {AdminApiRevokeUserSessionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokeUserSession(requestParameters: AdminApiRevokeUserSessionRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).revokeUserSession(requestParameters.revokeUserSessionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Revoke all user sessions
     * @param {AdminApiRevokeUserSessionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokeUserSessions(requestParameters: AdminApiRevokeUserSessionsRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).revokeUserSessions(requestParameters.listUserSessions1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set a user\'s password
     * @param {AdminApiSetUserPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setUserPassword(requestParameters: AdminApiSetUserPasswordRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).setUserPassword(requestParameters.setUserPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set the role of a user
     * @param {AdminApiSetUserRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setUserRole(requestParameters: AdminApiSetUserRoleRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).setUserRole(requestParameters.setUserRoleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unban a user
     * @param {AdminApiUnbanUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unbanUser(requestParameters: AdminApiUnbanUserRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).unbanUser(requestParameters.listUserSessions1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update a user\'s details
     * @param {AdminApiUpdateUser1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUser1(requestParameters: AdminApiUpdateUser1Request, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).updateUser1(requestParameters.updateUser1Request, options).then((request) => request(this.axios, this.basePath));
    }
}

