/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details> 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HealthCheckerControllerCheck200Response } from '../models';
// @ts-ignore
import type { HealthCheckerControllerCheck503Response } from '../models';
/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckerControllerCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckerControllerCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthCheckerControllerCheck200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckerControllerCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheckerControllerCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckerControllerCheck(options?: RawAxiosRequestConfig): AxiosPromise<HealthCheckerControllerCheck200Response> {
            return localVarFp.healthCheckerControllerCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheckerControllerCheck(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheckerControllerCheck(options).then((request) => request(this.axios, this.basePath));
    }
}

