/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details> 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateOrganizationDto } from '../models';
// @ts-ignore
import type { Order } from '../models';
// @ts-ignore
import type { OrganizationAlreadyBannedException } from '../models';
// @ts-ignore
import type { OrganizationBanDto } from '../models';
// @ts-ignore
import type { OrganizationControllerDeleteOrganizationV1403Response } from '../models';
// @ts-ignore
import type { OrganizationControllerGetOrganizationsV1200Response } from '../models';
// @ts-ignore
import type { OrganizationDto } from '../models';
// @ts-ignore
import type { OrganizationNotBannedException } from '../models';
// @ts-ignore
import type { OrganizationNotFoundException } from '../models';
// @ts-ignore
import type { OrganizationScopeAccessDeniedException } from '../models';
// @ts-ignore
import type { OrganizationSortField } from '../models';
// @ts-ignore
import type { UnauthorizedException } from '../models';
// @ts-ignore
import type { UpdateMyOrganizationDto } from '../models';
// @ts-ignore
import type { UpdateOrganizationDto } from '../models';
/**
 * OrganizationApi - axios parameter creator
 */
export const OrganizationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id Organization id
         * @param {OrganizationBanDto} organizationBanDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerBanOrganizationV1: async (id: string, organizationBanDto: OrganizationBanDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('organizationControllerBanOrganizationV1', 'id', id)
            // verify required parameter 'organizationBanDto' is not null or undefined
            assertParamExists('organizationControllerBanOrganizationV1', 'organizationBanDto', organizationBanDto)
            const localVarPath = `/api/v1/organizations/{id}/ban`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(organizationBanDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateOrganizationDto} createOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerCreateOrganizationV1: async (createOrganizationDto: CreateOrganizationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOrganizationDto' is not null or undefined
            assertParamExists('organizationControllerCreateOrganizationV1', 'createOrganizationDto', createOrganizationDto)
            const localVarPath = `/api/v1/organizations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOrganizationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerDeleteOrganizationV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('organizationControllerDeleteOrganizationV1', 'id', id)
            const localVarPath = `/api/v1/organizations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetMyOrganizationV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/organizations/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetOrganizationV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('organizationControllerGetOrganizationV1', 'id', id)
            const localVarPath = `/api/v1/organizations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Order} [order] 
         * @param {OrganizationSortField} [sort] Sort field
         * @param {number} [page] 
         * @param {number} [take] 
         * @param {string} [q] 
         * @param {string} [name] Filter by organization name
         * @param {boolean} [banned] Filter by banned status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetOrganizationsV1: async (order?: Order, sort?: OrganizationSortField, page?: number, take?: number, q?: string, name?: string, banned?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/organizations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (take !== undefined) {
                localVarQueryParameter['take'] = take;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (banned !== undefined) {
                localVarQueryParameter['banned'] = banned;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUnbanOrganizationV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('organizationControllerUnbanOrganizationV1', 'id', id)
            const localVarPath = `/api/v1/organizations/{id}/unban`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateMyOrganizationDto} updateMyOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUpdateMyOrganizationV1: async (updateMyOrganizationDto: UpdateMyOrganizationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateMyOrganizationDto' is not null or undefined
            assertParamExists('organizationControllerUpdateMyOrganizationV1', 'updateMyOrganizationDto', updateMyOrganizationDto)
            const localVarPath = `/api/v1/organizations/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMyOrganizationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {UpdateOrganizationDto} updateOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUpdateOrganizationV1: async (id: string, updateOrganizationDto: UpdateOrganizationDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('organizationControllerUpdateOrganizationV1', 'id', id)
            // verify required parameter 'updateOrganizationDto' is not null or undefined
            assertParamExists('organizationControllerUpdateOrganizationV1', 'updateOrganizationDto', updateOrganizationDto)
            const localVarPath = `/api/v1/organizations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOrganizationDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrganizationApi - functional programming interface
 */
export const OrganizationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrganizationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id Organization id
         * @param {OrganizationBanDto} organizationBanDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerBanOrganizationV1(id: string, organizationBanDto: OrganizationBanDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerBanOrganizationV1(id, organizationBanDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerBanOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateOrganizationDto} createOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerCreateOrganizationV1(createOrganizationDto: CreateOrganizationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerCreateOrganizationV1(createOrganizationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerCreateOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerDeleteOrganizationV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerDeleteOrganizationV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerDeleteOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerGetMyOrganizationV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerGetMyOrganizationV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerGetMyOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerGetOrganizationV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerGetOrganizationV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerGetOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Order} [order] 
         * @param {OrganizationSortField} [sort] Sort field
         * @param {number} [page] 
         * @param {number} [take] 
         * @param {string} [q] 
         * @param {string} [name] Filter by organization name
         * @param {boolean} [banned] Filter by banned status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerGetOrganizationsV1(order?: Order, sort?: OrganizationSortField, page?: number, take?: number, q?: string, name?: string, banned?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationControllerGetOrganizationsV1200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerGetOrganizationsV1(order, sort, page, take, q, name, banned, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerGetOrganizationsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerUnbanOrganizationV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerUnbanOrganizationV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerUnbanOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateMyOrganizationDto} updateMyOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerUpdateMyOrganizationV1(updateMyOrganizationDto: UpdateMyOrganizationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerUpdateMyOrganizationV1(updateMyOrganizationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerUpdateMyOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id Organization id
         * @param {UpdateOrganizationDto} updateOrganizationDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationControllerUpdateOrganizationV1(id: string, updateOrganizationDto: UpdateOrganizationDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationControllerUpdateOrganizationV1(id, updateOrganizationDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationApi.organizationControllerUpdateOrganizationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrganizationApi - factory interface
 */
export const OrganizationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrganizationApiFp(configuration)
    return {
        /**
         * 
         * @param {OrganizationApiOrganizationControllerBanOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerBanOrganizationV1(requestParameters: OrganizationApiOrganizationControllerBanOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.organizationControllerBanOrganizationV1(requestParameters.id, requestParameters.organizationBanDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerCreateOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerCreateOrganizationV1(requestParameters: OrganizationApiOrganizationControllerCreateOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationDto> {
            return localVarFp.organizationControllerCreateOrganizationV1(requestParameters.createOrganizationDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerDeleteOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerDeleteOrganizationV1(requestParameters: OrganizationApiOrganizationControllerDeleteOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.organizationControllerDeleteOrganizationV1(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetMyOrganizationV1(options?: RawAxiosRequestConfig): AxiosPromise<OrganizationDto> {
            return localVarFp.organizationControllerGetMyOrganizationV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerGetOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetOrganizationV1(requestParameters: OrganizationApiOrganizationControllerGetOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationDto> {
            return localVarFp.organizationControllerGetOrganizationV1(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerGetOrganizationsV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerGetOrganizationsV1(requestParameters: OrganizationApiOrganizationControllerGetOrganizationsV1Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationControllerGetOrganizationsV1200Response> {
            return localVarFp.organizationControllerGetOrganizationsV1(requestParameters.order, requestParameters.sort, requestParameters.page, requestParameters.take, requestParameters.q, requestParameters.name, requestParameters.banned, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerUnbanOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUnbanOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUnbanOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.organizationControllerUnbanOrganizationV1(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerUpdateMyOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUpdateMyOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUpdateMyOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationDto> {
            return localVarFp.organizationControllerUpdateMyOrganizationV1(requestParameters.updateMyOrganizationDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrganizationApiOrganizationControllerUpdateOrganizationV1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationControllerUpdateOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUpdateOrganizationV1Request, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationDto> {
            return localVarFp.organizationControllerUpdateOrganizationV1(requestParameters.id, requestParameters.updateOrganizationDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for organizationControllerBanOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerBanOrganizationV1Request {
    /**
     * Organization id
     */
    readonly id: string

    readonly organizationBanDto: OrganizationBanDto
}

/**
 * Request parameters for organizationControllerCreateOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerCreateOrganizationV1Request {
    readonly createOrganizationDto: CreateOrganizationDto
}

/**
 * Request parameters for organizationControllerDeleteOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerDeleteOrganizationV1Request {
    /**
     * Organization id
     */
    readonly id: string
}

/**
 * Request parameters for organizationControllerGetOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerGetOrganizationV1Request {
    /**
     * Organization id
     */
    readonly id: string
}

/**
 * Request parameters for organizationControllerGetOrganizationsV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerGetOrganizationsV1Request {
    readonly order?: Order

    /**
     * Sort field
     */
    readonly sort?: OrganizationSortField

    readonly page?: number

    readonly take?: number

    readonly q?: string

    /**
     * Filter by organization name
     */
    readonly name?: string

    /**
     * Filter by banned status
     */
    readonly banned?: boolean
}

/**
 * Request parameters for organizationControllerUnbanOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerUnbanOrganizationV1Request {
    /**
     * Organization id
     */
    readonly id: string
}

/**
 * Request parameters for organizationControllerUpdateMyOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerUpdateMyOrganizationV1Request {
    readonly updateMyOrganizationDto: UpdateMyOrganizationDto
}

/**
 * Request parameters for organizationControllerUpdateOrganizationV1 operation in OrganizationApi.
 */
export interface OrganizationApiOrganizationControllerUpdateOrganizationV1Request {
    /**
     * Organization id
     */
    readonly id: string

    readonly updateOrganizationDto: UpdateOrganizationDto
}

/**
 * OrganizationApi - object-oriented interface
 */
export class OrganizationApi extends BaseAPI {
    /**
     * 
     * @param {OrganizationApiOrganizationControllerBanOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerBanOrganizationV1(requestParameters: OrganizationApiOrganizationControllerBanOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerBanOrganizationV1(requestParameters.id, requestParameters.organizationBanDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerCreateOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerCreateOrganizationV1(requestParameters: OrganizationApiOrganizationControllerCreateOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerCreateOrganizationV1(requestParameters.createOrganizationDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerDeleteOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerDeleteOrganizationV1(requestParameters: OrganizationApiOrganizationControllerDeleteOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerDeleteOrganizationV1(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerGetMyOrganizationV1(options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerGetMyOrganizationV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerGetOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerGetOrganizationV1(requestParameters: OrganizationApiOrganizationControllerGetOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerGetOrganizationV1(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerGetOrganizationsV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerGetOrganizationsV1(requestParameters: OrganizationApiOrganizationControllerGetOrganizationsV1Request = {}, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerGetOrganizationsV1(requestParameters.order, requestParameters.sort, requestParameters.page, requestParameters.take, requestParameters.q, requestParameters.name, requestParameters.banned, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerUnbanOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerUnbanOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUnbanOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerUnbanOrganizationV1(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerUpdateMyOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerUpdateMyOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUpdateMyOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerUpdateMyOrganizationV1(requestParameters.updateMyOrganizationDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrganizationApiOrganizationControllerUpdateOrganizationV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationControllerUpdateOrganizationV1(requestParameters: OrganizationApiOrganizationControllerUpdateOrganizationV1Request, options?: RawAxiosRequestConfig) {
        return OrganizationApiFp(this.configuration).organizationControllerUpdateOrganizationV1(requestParameters.id, requestParameters.updateOrganizationDto, options).then((request) => request(this.axios, this.basePath));
    }
}

