/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details>
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { ApiAuthRbacCheckPermissionPost200Response } from "../models";
// @ts-ignore
import type { ApiAuthRbacCheckPermissionPostRequest } from "../models";
// @ts-ignore
import type { ApiAuthRbacPermissionsGet200Response } from "../models";
// @ts-ignore
import type { ApiAuthRbacRolePermissionsAssignPostRequest } from "../models";
// @ts-ignore
import type { ApiAuthRbacRolePutRequest } from "../models";
// @ts-ignore
import type { ApiAuthRbacRolesPostRequest } from "../models";
// @ts-ignore
import type { ApiAuthRbacUserPermissionsGet200Response } from "../models";
// @ts-ignore
import type { SocialSignIn400Response } from "../models";
// @ts-ignore
import type { SocialSignIn403Response } from "../models";
/**
 * RbacApi - axios parameter creator
 */
export const RbacApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {ApiAuthRbacCheckPermissionPostRequest} [apiAuthRbacCheckPermissionPostRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacCheckPermissionPost: async (
      apiAuthRbacCheckPermissionPostRequest?: ApiAuthRbacCheckPermissionPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/check-permission`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiAuthRbacCheckPermissionPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string | null} [limit]
     * @param {string | null} [offset]
     * @param {string | null} [sortBy]
     * @param {string | null} [sortDirection]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacPermissionsGet: async (
      limit?: string | null,
      offset?: string | null,
      sortBy?: string | null,
      sortDirection?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/permissions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["sortBy"] = sortBy;
      }

      if (sortDirection !== undefined) {
        localVarQueryParameter["sortDirection"] = sortDirection;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRoleDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/role`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "DELETE", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [roleId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRoleGet: async (
      roleId?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/role`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (roleId !== undefined) {
        localVarQueryParameter["roleId"] = roleId;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiAuthRbacRolePermissionsAssignPostRequest} apiAuthRbacRolePermissionsAssignPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsAssignPost: async (
      apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiAuthRbacRolePermissionsAssignPostRequest' is not null or undefined
      assertParamExists(
        "apiAuthRbacRolePermissionsAssignPost",
        "apiAuthRbacRolePermissionsAssignPostRequest",
        apiAuthRbacRolePermissionsAssignPostRequest,
      );
      const localVarPath = `/api/auth/rbac/role-permissions/assign`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiAuthRbacRolePermissionsAssignPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [roleId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsGet: async (
      roleId?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/role-permissions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (roleId !== undefined) {
        localVarQueryParameter["roleId"] = roleId;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiAuthRbacRolePermissionsAssignPostRequest} apiAuthRbacRolePermissionsAssignPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsRemovePost: async (
      apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiAuthRbacRolePermissionsAssignPostRequest' is not null or undefined
      assertParamExists(
        "apiAuthRbacRolePermissionsRemovePost",
        "apiAuthRbacRolePermissionsAssignPostRequest",
        apiAuthRbacRolePermissionsAssignPostRequest,
      );
      const localVarPath = `/api/auth/rbac/role-permissions/remove`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiAuthRbacRolePermissionsAssignPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiAuthRbacRolePutRequest} apiAuthRbacRolePutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePut: async (
      apiAuthRbacRolePutRequest: ApiAuthRbacRolePutRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiAuthRbacRolePutRequest' is not null or undefined
      assertParamExists(
        "apiAuthRbacRolePut",
        "apiAuthRbacRolePutRequest",
        apiAuthRbacRolePutRequest,
      );
      const localVarPath = `/api/auth/rbac/role`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "PUT", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiAuthRbacRolePutRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string | null} [limit]
     * @param {string | null} [offset]
     * @param {string | null} [sortBy]
     * @param {string | null} [sortDirection]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolesGet: async (
      limit?: string | null,
      offset?: string | null,
      sortBy?: string | null,
      sortDirection?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/roles`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["sortBy"] = sortBy;
      }

      if (sortDirection !== undefined) {
        localVarQueryParameter["sortDirection"] = sortDirection;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ApiAuthRbacRolesPostRequest} apiAuthRbacRolesPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolesPost: async (
      apiAuthRbacRolesPostRequest: ApiAuthRbacRolesPostRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'apiAuthRbacRolesPostRequest' is not null or undefined
      assertParamExists(
        "apiAuthRbacRolesPost",
        "apiAuthRbacRolesPostRequest",
        apiAuthRbacRolesPostRequest,
      );
      const localVarPath = `/api/auth/rbac/roles`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        apiAuthRbacRolesPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacSyncPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/sync`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacUserPermissionsGet: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/rbac/user-permissions`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RbacApi - functional programming interface
 */
export const RbacApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RbacApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {ApiAuthRbacCheckPermissionPostRequest} [apiAuthRbacCheckPermissionPostRequest]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacCheckPermissionPost(
      apiAuthRbacCheckPermissionPostRequest?: ApiAuthRbacCheckPermissionPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiAuthRbacCheckPermissionPost200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacCheckPermissionPost(
        apiAuthRbacCheckPermissionPostRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacCheckPermissionPost"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string | null} [limit]
     * @param {string | null} [offset]
     * @param {string | null} [sortBy]
     * @param {string | null} [sortDirection]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacPermissionsGet(
      limit?: string | null,
      offset?: string | null,
      sortBy?: string | null,
      sortDirection?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiAuthRbacPermissionsGet200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacPermissionsGet(
        limit,
        offset,
        sortBy,
        sortDirection,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacPermissionsGet"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRoleDelete(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRoleDelete(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRoleDelete"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} [roleId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRoleGet(
      roleId?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRoleGet(roleId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRoleGet"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiAuthRbacRolePermissionsAssignPostRequest} apiAuthRbacRolePermissionsAssignPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolePermissionsAssignPost(
      apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiAuthRbacRolePermissionsAssignPost(
          apiAuthRbacRolePermissionsAssignPostRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolePermissionsAssignPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} [roleId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolePermissionsGet(
      roleId?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiAuthRbacPermissionsGet200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRolePermissionsGet(
        roleId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolePermissionsGet"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiAuthRbacRolePermissionsAssignPostRequest} apiAuthRbacRolePermissionsAssignPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolePermissionsRemovePost(
      apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiAuthRbacRolePermissionsRemovePost(
          apiAuthRbacRolePermissionsAssignPostRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolePermissionsRemovePost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiAuthRbacRolePutRequest} apiAuthRbacRolePutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolePut(
      apiAuthRbacRolePutRequest: ApiAuthRbacRolePutRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRolePut(
        apiAuthRbacRolePutRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolePut"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string | null} [limit]
     * @param {string | null} [offset]
     * @param {string | null} [sortBy]
     * @param {string | null} [sortDirection]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolesGet(
      limit?: string | null,
      offset?: string | null,
      sortBy?: string | null,
      sortDirection?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRolesGet(
        limit,
        offset,
        sortBy,
        sortDirection,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolesGet"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {ApiAuthRbacRolesPostRequest} apiAuthRbacRolesPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacRolesPost(
      apiAuthRbacRolesPostRequest: ApiAuthRbacRolesPostRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacRolesPost(
        apiAuthRbacRolesPostRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacRolesPost"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacSyncPost(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRbacSyncPost(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacSyncPost"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiAuthRbacUserPermissionsGet(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ApiAuthRbacUserPermissionsGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiAuthRbacUserPermissionsGet(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["RbacApi.apiAuthRbacUserPermissionsGet"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * RbacApi - factory interface
 */
export const RbacApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = RbacApiFp(configuration);
  return {
    /**
     *
     * @param {RbacApiApiAuthRbacCheckPermissionPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacCheckPermissionPost(
      requestParameters: RbacApiApiAuthRbacCheckPermissionPostRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ApiAuthRbacCheckPermissionPost200Response> {
      return localVarFp
        .apiAuthRbacCheckPermissionPost(
          requestParameters.apiAuthRbacCheckPermissionPostRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacPermissionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacPermissionsGet(
      requestParameters: RbacApiApiAuthRbacPermissionsGetRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ApiAuthRbacPermissionsGet200Response> {
      return localVarFp
        .apiAuthRbacPermissionsGet(
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.sortBy,
          requestParameters.sortDirection,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRoleDelete(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.apiAuthRbacRoleDelete(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRoleGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRoleGet(
      requestParameters: RbacApiApiAuthRbacRoleGetRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRoleGet(requestParameters.roleId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolePermissionsAssignPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsAssignPost(
      requestParameters: RbacApiApiAuthRbacRolePermissionsAssignPostRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRolePermissionsAssignPost(
          requestParameters.apiAuthRbacRolePermissionsAssignPostRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolePermissionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsGet(
      requestParameters: RbacApiApiAuthRbacRolePermissionsGetRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ApiAuthRbacPermissionsGet200Response> {
      return localVarFp
        .apiAuthRbacRolePermissionsGet(requestParameters.roleId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolePermissionsRemovePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePermissionsRemovePost(
      requestParameters: RbacApiApiAuthRbacRolePermissionsRemovePostRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRolePermissionsRemovePost(
          requestParameters.apiAuthRbacRolePermissionsAssignPostRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolePutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolePut(
      requestParameters: RbacApiApiAuthRbacRolePutRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRolePut(requestParameters.apiAuthRbacRolePutRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolesGet(
      requestParameters: RbacApiApiAuthRbacRolesGetRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRolesGet(
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.sortBy,
          requestParameters.sortDirection,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {RbacApiApiAuthRbacRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacRolesPost(
      requestParameters: RbacApiApiAuthRbacRolesPostRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .apiAuthRbacRolesPost(requestParameters.apiAuthRbacRolesPostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacSyncPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.apiAuthRbacSyncPost(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAuthRbacUserPermissionsGet(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ApiAuthRbacUserPermissionsGet200Response> {
      return localVarFp
        .apiAuthRbacUserPermissionsGet(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for apiAuthRbacCheckPermissionPost operation in RbacApi.
 */
export interface RbacApiApiAuthRbacCheckPermissionPostRequest {
  readonly apiAuthRbacCheckPermissionPostRequest?: ApiAuthRbacCheckPermissionPostRequest;
}

/**
 * Request parameters for apiAuthRbacPermissionsGet operation in RbacApi.
 */
export interface RbacApiApiAuthRbacPermissionsGetRequest {
  readonly limit?: string | null;

  readonly offset?: string | null;

  readonly sortBy?: string | null;

  readonly sortDirection?: string | null;
}

/**
 * Request parameters for apiAuthRbacRoleGet operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRoleGetRequest {
  readonly roleId?: string;
}

/**
 * Request parameters for apiAuthRbacRolePermissionsAssignPost operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolePermissionsAssignPostRequest {
  readonly apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest;
}

/**
 * Request parameters for apiAuthRbacRolePermissionsGet operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolePermissionsGetRequest {
  readonly roleId?: string;
}

/**
 * Request parameters for apiAuthRbacRolePermissionsRemovePost operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolePermissionsRemovePostRequest {
  readonly apiAuthRbacRolePermissionsAssignPostRequest: ApiAuthRbacRolePermissionsAssignPostRequest;
}

/**
 * Request parameters for apiAuthRbacRolePut operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolePutRequest {
  readonly apiAuthRbacRolePutRequest: ApiAuthRbacRolePutRequest;
}

/**
 * Request parameters for apiAuthRbacRolesGet operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolesGetRequest {
  readonly limit?: string | null;

  readonly offset?: string | null;

  readonly sortBy?: string | null;

  readonly sortDirection?: string | null;
}

/**
 * Request parameters for apiAuthRbacRolesPost operation in RbacApi.
 */
export interface RbacApiApiAuthRbacRolesPostRequest {
  readonly apiAuthRbacRolesPostRequest: ApiAuthRbacRolesPostRequest;
}

/**
 * RbacApi - object-oriented interface
 */
export class RbacApi extends BaseAPI {
  /**
   *
   * @param {RbacApiApiAuthRbacCheckPermissionPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacCheckPermissionPost(
    requestParameters: RbacApiApiAuthRbacCheckPermissionPostRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacCheckPermissionPost(
        requestParameters.apiAuthRbacCheckPermissionPostRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacPermissionsGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacPermissionsGet(
    requestParameters: RbacApiApiAuthRbacPermissionsGetRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacPermissionsGet(
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.sortBy,
        requestParameters.sortDirection,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRoleDelete(options?: RawAxiosRequestConfig) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRoleDelete(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRoleGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRoleGet(
    requestParameters: RbacApiApiAuthRbacRoleGetRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRoleGet(requestParameters.roleId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolePermissionsAssignPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolePermissionsAssignPost(
    requestParameters: RbacApiApiAuthRbacRolePermissionsAssignPostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolePermissionsAssignPost(
        requestParameters.apiAuthRbacRolePermissionsAssignPostRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolePermissionsGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolePermissionsGet(
    requestParameters: RbacApiApiAuthRbacRolePermissionsGetRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolePermissionsGet(requestParameters.roleId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolePermissionsRemovePostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolePermissionsRemovePost(
    requestParameters: RbacApiApiAuthRbacRolePermissionsRemovePostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolePermissionsRemovePost(
        requestParameters.apiAuthRbacRolePermissionsAssignPostRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolePutRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolePut(
    requestParameters: RbacApiApiAuthRbacRolePutRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolePut(requestParameters.apiAuthRbacRolePutRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolesGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolesGet(
    requestParameters: RbacApiApiAuthRbacRolesGetRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolesGet(
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.sortBy,
        requestParameters.sortDirection,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {RbacApiApiAuthRbacRolesPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacRolesPost(
    requestParameters: RbacApiApiAuthRbacRolesPostRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacRolesPost(requestParameters.apiAuthRbacRolesPostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacSyncPost(options?: RawAxiosRequestConfig) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacSyncPost(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public apiAuthRbacUserPermissionsGet(options?: RawAxiosRequestConfig) {
    return RbacApiFp(this.configuration)
      .apiAuthRbacUserPermissionsGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
