/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details>
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { CreateUserDto } from "../models";
// @ts-ignore
import type { Order } from "../models";
// @ts-ignore
import type { UnauthorizedException } from "../models";
// @ts-ignore
import type { UpdateCurrentUserDto } from "../models";
// @ts-ignore
import type { UpdateUserDto } from "../models";
// @ts-ignore
import type { UserControllerGetUsersV1200Response } from "../models";
// @ts-ignore
import type { UserDto } from "../models";
// @ts-ignore
import type { UserSort } from "../models";
/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerAdminV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/users/admin`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerBlockUserV1: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("userControllerBlockUserV1", "id", id);
      const localVarPath = `/api/v1/users/{id}/block`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {CreateUserDto} createUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerCreateUserV1: async (
      createUserDto: CreateUserDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createUserDto' is not null or undefined
      assertParamExists("userControllerCreateUserV1", "createUserDto", createUserDto);
      const localVarPath = `/api/v1/users`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createUserDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerDeleteUserV1: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("userControllerDeleteUserV1", "id", id);
      const localVarPath = `/api/v1/users/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "DELETE", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetCurrentUserV1: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/users/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetUserV1: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("userControllerGetUserV1", "id", id);
      const localVarPath = `/api/v1/users/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {Order} [order]
     * @param {UserSort} [sort]
     * @param {number} [page]
     * @param {number} [take]
     * @param {string} [q]
     * @param {string} [role]
     * @param {boolean} [isBlocked]
     * @param {boolean} [isEmailVerified]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetUsersV1: async (
      order?: Order,
      sort?: UserSort,
      page?: number,
      take?: number,
      q?: string,
      role?: string,
      isBlocked?: boolean,
      isEmailVerified?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/users`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (take !== undefined) {
        localVarQueryParameter["take"] = take;
      }

      if (q !== undefined) {
        localVarQueryParameter["q"] = q;
      }

      if (role !== undefined) {
        localVarQueryParameter["role"] = role;
      }

      if (isBlocked !== undefined) {
        localVarQueryParameter["isBlocked"] = isBlocked;
      }

      if (isEmailVerified !== undefined) {
        localVarQueryParameter["isEmailVerified"] = isEmailVerified;
      }

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUnblockUserV1: async (
      id: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("userControllerUnblockUserV1", "id", id);
      const localVarPath = `/api/v1/users/{id}/unblock`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {UpdateCurrentUserDto} updateCurrentUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUpdateCurrentUserV1: async (
      updateCurrentUserDto: UpdateCurrentUserDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'updateCurrentUserDto' is not null or undefined
      assertParamExists(
        "userControllerUpdateCurrentUserV1",
        "updateCurrentUserDto",
        updateCurrentUserDto,
      );
      const localVarPath = `/api/v1/users/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "PATCH", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateCurrentUserDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id User id
     * @param {UpdateUserDto} updateUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUpdateUserV1: async (
      id: string,
      updateUserDto: UpdateUserDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("userControllerUpdateUserV1", "id", id);
      // verify required parameter 'updateUserDto' is not null or undefined
      assertParamExists("userControllerUpdateUserV1", "updateUserDto", updateUserDto);
      const localVarPath = `/api/v1/users/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "PATCH", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateUserDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerAdminV1(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerAdminV1(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerAdminV1"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerBlockUserV1(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerBlockUserV1(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerBlockUserV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {CreateUserDto} createUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerCreateUserV1(
      createUserDto: CreateUserDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerCreateUserV1(
        createUserDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerCreateUserV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerDeleteUserV1(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerDeleteUserV1(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerDeleteUserV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerGetCurrentUserV1(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.userControllerGetCurrentUserV1(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerGetCurrentUserV1"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerGetUserV1(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetUserV1(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerGetUserV1"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {Order} [order]
     * @param {UserSort} [sort]
     * @param {number} [page]
     * @param {number} [take]
     * @param {string} [q]
     * @param {string} [role]
     * @param {boolean} [isBlocked]
     * @param {boolean} [isEmailVerified]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerGetUsersV1(
      order?: Order,
      sort?: UserSort,
      page?: number,
      take?: number,
      q?: string,
      role?: string,
      isBlocked?: boolean,
      isEmailVerified?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<UserControllerGetUsersV1200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerGetUsersV1(
        order,
        sort,
        page,
        take,
        q,
        role,
        isBlocked,
        isEmailVerified,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerGetUsersV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id User id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerUnblockUserV1(
      id: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerUnblockUserV1(
        id,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerUnblockUserV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {UpdateCurrentUserDto} updateCurrentUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerUpdateCurrentUserV1(
      updateCurrentUserDto: UpdateCurrentUserDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerUpdateCurrentUserV1(
        updateCurrentUserDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerUpdateCurrentUserV1"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id User id
     * @param {UpdateUserDto} updateUserDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userControllerUpdateUserV1(
      id: string,
      updateUserDto: UpdateUserDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerUpdateUserV1(
        id,
        updateUserDto,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["UsersApi.userControllerUpdateUserV1"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = UsersApiFp(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerAdminV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.userControllerAdminV1(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerBlockUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerBlockUserV1(
      requestParameters: UsersApiUserControllerBlockUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .userControllerBlockUserV1(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerCreateUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerCreateUserV1(
      requestParameters: UsersApiUserControllerCreateUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserDto> {
      return localVarFp
        .userControllerCreateUserV1(requestParameters.createUserDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerDeleteUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerDeleteUserV1(
      requestParameters: UsersApiUserControllerDeleteUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .userControllerDeleteUserV1(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetCurrentUserV1(options?: RawAxiosRequestConfig): AxiosPromise<UserDto> {
      return localVarFp
        .userControllerGetCurrentUserV1(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerGetUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetUserV1(
      requestParameters: UsersApiUserControllerGetUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserDto> {
      return localVarFp
        .userControllerGetUserV1(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerGetUsersV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerGetUsersV1(
      requestParameters: UsersApiUserControllerGetUsersV1Request = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserControllerGetUsersV1200Response> {
      return localVarFp
        .userControllerGetUsersV1(
          requestParameters.order,
          requestParameters.sort,
          requestParameters.page,
          requestParameters.take,
          requestParameters.q,
          requestParameters.role,
          requestParameters.isBlocked,
          requestParameters.isEmailVerified,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerUnblockUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUnblockUserV1(
      requestParameters: UsersApiUserControllerUnblockUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .userControllerUnblockUserV1(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerUpdateCurrentUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUpdateCurrentUserV1(
      requestParameters: UsersApiUserControllerUpdateCurrentUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserDto> {
      return localVarFp
        .userControllerUpdateCurrentUserV1(requestParameters.updateCurrentUserDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {UsersApiUserControllerUpdateUserV1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userControllerUpdateUserV1(
      requestParameters: UsersApiUserControllerUpdateUserV1Request,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserDto> {
      return localVarFp
        .userControllerUpdateUserV1(requestParameters.id, requestParameters.updateUserDto, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for userControllerBlockUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerBlockUserV1Request {
  /**
   * User id
   */
  readonly id: string;
}

/**
 * Request parameters for userControllerCreateUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerCreateUserV1Request {
  readonly createUserDto: CreateUserDto;
}

/**
 * Request parameters for userControllerDeleteUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerDeleteUserV1Request {
  /**
   * User id
   */
  readonly id: string;
}

/**
 * Request parameters for userControllerGetUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerGetUserV1Request {
  /**
   * User id
   */
  readonly id: string;
}

/**
 * Request parameters for userControllerGetUsersV1 operation in UsersApi.
 */
export interface UsersApiUserControllerGetUsersV1Request {
  readonly order?: Order;

  readonly sort?: UserSort;

  readonly page?: number;

  readonly take?: number;

  readonly q?: string;

  readonly role?: string;

  readonly isBlocked?: boolean;

  readonly isEmailVerified?: boolean;
}

/**
 * Request parameters for userControllerUnblockUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerUnblockUserV1Request {
  /**
   * User id
   */
  readonly id: string;
}

/**
 * Request parameters for userControllerUpdateCurrentUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerUpdateCurrentUserV1Request {
  readonly updateCurrentUserDto: UpdateCurrentUserDto;
}

/**
 * Request parameters for userControllerUpdateUserV1 operation in UsersApi.
 */
export interface UsersApiUserControllerUpdateUserV1Request {
  /**
   * User id
   */
  readonly id: string;

  readonly updateUserDto: UpdateUserDto;
}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerAdminV1(options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .userControllerAdminV1(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerBlockUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerBlockUserV1(
    requestParameters: UsersApiUserControllerBlockUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerBlockUserV1(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerCreateUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerCreateUserV1(
    requestParameters: UsersApiUserControllerCreateUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerCreateUserV1(requestParameters.createUserDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerDeleteUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerDeleteUserV1(
    requestParameters: UsersApiUserControllerDeleteUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerDeleteUserV1(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerGetCurrentUserV1(options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .userControllerGetCurrentUserV1(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerGetUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerGetUserV1(
    requestParameters: UsersApiUserControllerGetUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerGetUserV1(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerGetUsersV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerGetUsersV1(
    requestParameters: UsersApiUserControllerGetUsersV1Request = {},
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerGetUsersV1(
        requestParameters.order,
        requestParameters.sort,
        requestParameters.page,
        requestParameters.take,
        requestParameters.q,
        requestParameters.role,
        requestParameters.isBlocked,
        requestParameters.isEmailVerified,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerUnblockUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerUnblockUserV1(
    requestParameters: UsersApiUserControllerUnblockUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerUnblockUserV1(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerUpdateCurrentUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerUpdateCurrentUserV1(
    requestParameters: UsersApiUserControllerUpdateCurrentUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerUpdateCurrentUserV1(requestParameters.updateCurrentUserDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {UsersApiUserControllerUpdateUserV1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public userControllerUpdateUserV1(
    requestParameters: UsersApiUserControllerUpdateUserV1Request,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .userControllerUpdateUserV1(requestParameters.id, requestParameters.updateUserDto, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
