/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details> 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User object with phone number details, null if no user is created or found
 */
export interface ApiAuthPhoneNumberVerifyPost200ResponseUser {
    /**
     * Unique identifier of the user
     */
    'id': string;
    /**
     * User\'s email address
     */
    'email'?: string;
    /**
     * Whether the email is verified
     */
    'emailVerified'?: boolean;
    /**
     * User\'s name
     */
    'name'?: string;
    /**
     * User\'s profile image URL
     */
    'image'?: string;
    /**
     * User\'s phone number
     */
    'phoneNumber': string;
    /**
     * Whether the phone number is verified
     */
    'phoneNumberVerified': boolean;
    /**
     * Timestamp when the user was created
     */
    'createdAt': string;
    /**
     * Timestamp when the user was last updated
     */
    'updatedAt': string;
}

