/* tslint:disable */
/* eslint-disable */
/**
 * API
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**  - \\`GET /<resources>/\\`   - Get the list of **<resources>** as admin - \\`GET /user/<user_id>/<resources>/\\`   - Get the list of **<resources>** for a given **<user_id>**   - Output a **403** if logged user is not **<user_id>**  **Detail:**  - \\`GET /<resources>/<resource_id>\\`   - Get the detail for **<resources>** of id **<resource_id>**   - Output a **404** if not found - \\`GET /user/<user_id>/<resources>/<resource_id>\\`   - Get the list of **<resources>** for a given **user_id**   - Output a **404** if not found   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**  - \\`<METHOD>\\` is:   - **POST** for creation   - **PATCH** for update (one or more fields)   - **PUT** for replacement (all fields, not used)   - **DELETE** for suppression (all fields, not used) - \\`<METHOD> /<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as admin   - Output a **400** if **<resource_id>** conflicts with existing **<resources>** - \\`<METHOD> /user/<user_id>/<resources>/<resource_id>\\`   - Create **<resources>** with id **<resource_id>** as a given **user_id**   - Output a **409** if **<resource_id>** conflicts with existing **<resources>**   - Output a **403** if:     - Logged user is not **<user_id>**     - The **<user_id>** have no access to **<resource_id>**  </p> </details> 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationScopeAccessDenied2Exception {
    'statusCode': OrganizationScopeAccessDenied2ExceptionStatusCodeEnum;
    'message': OrganizationScopeAccessDenied2ExceptionMessageEnum;
    'error': OrganizationScopeAccessDenied2ExceptionErrorEnum;
}

export const OrganizationScopeAccessDenied2ExceptionStatusCodeEnum = {
    NUMBER_403: 403
} as const;

export type OrganizationScopeAccessDenied2ExceptionStatusCodeEnum = typeof OrganizationScopeAccessDenied2ExceptionStatusCodeEnum[keyof typeof OrganizationScopeAccessDenied2ExceptionStatusCodeEnum];
export const OrganizationScopeAccessDenied2ExceptionMessageEnum = {
    ErrorOrganizationScopeAccessDenied2: 'error.organization.scopeAccessDenied2'
} as const;

export type OrganizationScopeAccessDenied2ExceptionMessageEnum = typeof OrganizationScopeAccessDenied2ExceptionMessageEnum[keyof typeof OrganizationScopeAccessDenied2ExceptionMessageEnum];
export const OrganizationScopeAccessDenied2ExceptionErrorEnum = {
    Forbidden: 'Forbidden'
} as const;

export type OrganizationScopeAccessDenied2ExceptionErrorEnum = typeof OrganizationScopeAccessDenied2ExceptionErrorEnum[keyof typeof OrganizationScopeAccessDenied2ExceptionErrorEnum];


